spring:
  cloud:
    config:
      server:
        git:
          default-label: configserver
          uri: https://github.com/bsolutec/microservices-bsucode
          search-paths: config-data
          
  application:
    name: config-microservice

server:
  port: 8081